# Generated by Django 3.2.8 on 2021-11-12 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 9, 24, 26, 374960), verbose_name='date published'),
        ),
    ]
